import "@/styles/globals.css";
import { SideBar, Header, ClientProvider } from "@/components";

export const metadata = {
    title: "Web Amazon",
    description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="flex bg-[#F7FBFF] h-screen">
                <ClientProvider>
                    {/* SIDEBAR */}
                    <SideBar />
                    <main className="p-10 max-w-7xl w-full mx-auto overflow-y-auto">
                        {/* HEADER */}
                        <Header />
                        {children}
                    </main>
                </ClientProvider>
            </body>
        </html>
    );
}
